spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_name
    username: root
    password: db_root_password
    ddl-auto: validate
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE

omdb:
  api:
    key: 823741de
    url: http://www.omdbapi.com